Module creation and ES6 Code Implementations
cancelei/Awesome-books pull request #8
Opened 2023-06-12 21:11 UTC by cancelei

Hello reviewer,

You can find the APP: Book List in this part of the project. 

Its primary function is to store key pair values: Author and Book Title, for future reading and referencing. It is not production ready.

Highlights:
- Moved JS code to Modules/app.js and other .js files in the new folder.
- Loading script with index.js, with import and export in Class and functions.
- Updated Readme File and Linter's Passing.

Happy review!

2023-06-14 23:00 UTC, Shedrack-Sunday requested changes
Hello @cancelei    👋 

# CHANGES REQUIRED ♻️

Great work on the project 👏
You've done extremely well so far in this project,  However, there are some adjustments you need to make to move to the next project. 💯

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights   
- Good use of GitHub features ✔️  
  
# Required Changes  🌵 

- [ ] You made some efforts in the implementations which I must say is a job well done. However, there are some issues  I suggest   you make In line with the requirements 

_Check the comments for a detailed review 

# Optional suggestions 

Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing really improves your application.

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-06-14 23:00 UTC, Shedrack-Sunday commented on index.js
> +// console.log(nav_contact, nav_add, nav_list);
- [x] Kindly remove this portion of Code comment from your codebase. It can lead to confusion, and it also will lead to a clustered codebase if done frequently 👍

2023-06-14 23:10 UTC, cancelei commented on index.js
> +// console.log(nav_contact, nav_add, nav_list);
Just Did that! @Shedrack-Sunday

2023-06-15 13:25 UTC, omarsalem7 approved these changes
Hi @cancelei 😊, 
# STATUS: APPROVED! 🥇 💯 

<!--- ![giphy](https://media.giphy.com/media/n5VaQoW39Z9S0/giphy.gif) -->

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 🚀 
Congratulations! 🎉 

## Highlights
✅ Project has met all the technical aspects you needed for this project. Keep rocking! 

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-20 21:46 UTC, merged